# Generated by Django 3.0.5 on 2024-12-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20241205_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='head',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='total_students',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
