# Generated by Django 3.0.5 on 2024-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20241206_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
