# Generated by Django 3.0.5 on 2024-12-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20241206_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/student face/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fingerprint_data',
            field=models.FileField(blank=True, null=True, upload_to='media/student fingerprint/'),
        ),
    ]
